export const CLIENT_MODS = [
    "aero",
    "aliucord",
    "betterDiscord",
    "bunny",
    "enmity",
    "goosemod",
    "kettu",
    "raincord",
    "replugged",
    "revenge",
    "shelter",
    "suncord",
    "velocity",
    "vencord",
    "vendetta",
];
